### PR TITLE
Add project

### PR DESCRIPTION
**Pull request by sqwxl**
I'd like to humbly ask if can add my hobby project to the list? It's still a work-in-progress, but I'd love to get some eyes on it and maybe some feedback. Cheers.

### CODE REVIEW

**Comment by benjamin-kirkbride** [comment]
Hmm, so I have mixed feelings about this.

Pros:
- it is highly relevant; it uses the stack that I would recommend someone use and so it is a great example of the kind of projects we are looking to showcase
- it is fairly far along as far as I can see

Cons:
- it is not a demo/tutorial type project, so it's usefulness for beginners is somewhat limited
- it is not a finished, "live" project, so it's usefulness for an intermediate or advanced programmer is somewhat limited
- most hobby projects get abandoned (nothing personal at all, I have a million abandoned projects :smile:) and this in turn would make this list look outdated/abandoned possibly, if we have too many "old" or "abandoned" examples. This would be mitigated by https://github.com/PyHAT-stack/awesome-python-htmx/issues/7
  - I could see people being hurt/offended if we cull their links/projects due to age (not saying you will, but we are setting a precedent with this decision)

I am leaning towards yes, but my question for you @sqwxl is this: how long since you have done anything substantial with the project would you say would be fair for us to cull it from the list without you being hurt/offended by that?

**Comment by benjamin-kirkbride** [comment]
curious to hear @tataraba's opinions as well

**Comment by sqwxl** [comment]
Sure your concerns are totally reasonable. I was planning on deploying a demo soon so that ppl could check out the "finished" product.
As far as getting offended, I'm not the type. This repo is yours and I come to you in all humility; if you want to remove me from the list for any reason I won't mind. To be frank I might not even notice :sweat_smile:
Thanks for taking the time to look at the project in any case!

**Comment by benjamin-kirkbride** [comment]
I say if you have a demo then I'm happy to include it here, are you okay with waiting until then?

**Comment by tataraba** [comment]
Just piping in here and saying that I agree with the comments @benjamin-kirkbride stated earlier. I actually have a work-in-progress project that I've started (and stopped) a few times, but have hesitated to include it here for the same reasons. I'd like to at least have it at a point where someone could replicate it and use it going forward, along with useful documentation to guide anyone who might want to use it as a starting off point.

But in essence, I think "demo" also fulfills part of the intention of the repo, which is to show practical/useful ways to implement this stack. So I'm in favor of including it once it is in "demo" status.

Oh and also, thank you so much for engaging. I look forward to seeing what you're working on!

**Pull request merged**
